<?php

namespace Database\Seeders;

use App\Models\Integration;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IntegrationTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {


    $integrations = array(
      array('id' => '2', 'slug' => 'facebook-page-sync', 'title' => 'Facebook Page Sync', 'preview' => '/demo/JDLdmMmhTOXrdmThkylV.png', 'preview_2' => '/demo/BBBSkATufZ0O6E8pmNo7.jpg', 'bg_color' => '#c6eefb', 'short_description' => 'Transfer contacts information
                  between Meta', 'long_description' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'meta' => '{"title":"Facebook Page Sync","image":null,"description":null,"tags":null}', 'is_active' => '1', 'is_featured' => '1', 'created_at' => '2023-11-23 03:53:41', 'updated_at' => '2024-08-15 05:07:00'),
      array('id' => '3', 'slug' => 'mailchimp-contacts-sync', 'title' => 'Twitter Account Sync', 'preview' => '/demo/l49Gud2M0itGD697X8Rh.png', 'preview_2' => '/demo/BBBSkATufZ0O6E8pmNo7.jpg', 'bg_color' => '#000000', 'short_description' => 'Transfer contacts information
                  between Twitter', 'long_description' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'meta' => '{"title":"Twitter Account Sync","image":null,"description":null,"tags":null}', 'is_active' => '1', 'is_featured' => '1', 'created_at' => '2023-11-24 03:53:41', 'updated_at' => '2024-08-15 05:19:46'),
      array('id' => '4', 'slug' => 'salesforce-contacts-sync', 'title' => 'Linkedin Sync', 'preview' => '/demo/fsaBjNoHBOaSxY0SJJC7.png', 'preview_2' => '/demo/BBBSkATufZ0O6E8pmNo7.jpg', 'bg_color' => '#007ab9', 'short_description' => 'Transfer contacts information between Linkedin', 'long_description' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'meta' => '{"title":"Linkedin Account Sync","image":null,"description":null,"tags":null}', 'is_active' => '1', 'is_featured' => '1', 'created_at' => '2023-11-25 03:53:41', 'updated_at' => '2024-08-15 05:22:00'),
      array('id' => '5', 'slug' => 'zendesk-integration', 'title' => 'Instagram Sync', 'preview' => '/demo/y9MdpYe7PULnS886Klp9.png', 'preview_2' => '/demo/BBBSkATufZ0O6E8pmNo7.jpg', 'bg_color' => '#fff5cf', 'short_description' => 'Transfer contacts information
                  between Instagram', 'long_description' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'meta' => '{"title":"Instagram Contacts Sync","image":null,"description":null,"tags":null}', 'is_active' => '1', 'is_featured' => '1', 'created_at' => '2023-11-26 03:53:41', 'updated_at' => '2024-08-15 05:27:31')
    );


    Integration::insert($integrations);
  }
}
