<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {

    $services = array(
      array('id' => '1', 'category_id' => '66', 'title' => 'Artificial Intelligence Driven Strategies and Analytics with SocialAI', 'slug' => 'generate-manage-and-convert-leads-into-customers-automatically-1', 'icon' => '/demo/GeKbiduMHwHxy83bzpEw.png', 'preview' => '/demo/o0er6N868JXW0L1ozOL9.jpg', 'overview' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'description' => NULL, 'faqs' => NULL, 'is_active' => '1', 'is_featured' => '1', 'meta' => '{"title":"Artificial Intelligence driven strategies","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}', 'created_at' => '2023-11-01 02:57:49', 'updated_at' => '2024-08-15 04:53:05'),
      array('id' => '2', 'category_id' => '70', 'title' => 'Multiplatform publishing', 'slug' => 'automate-workflows-and-monitor-your-sales-1', 'icon' => '/demo/tGKDpkqENf0Cvo3eMUva.svg', 'preview' => '/demo/8NDSdm6BWE5KaFh01q19.jpg', 'overview' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'description' => NULL, 'faqs' => NULL, 'is_active' => '1', 'is_featured' => '1', 'meta' => '{"title":"Generate, Manage, and Convert leads into Customers. Automatically","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}', 'created_at' => '2023-11-02 02:57:49', 'updated_at' => '2024-08-15 04:57:02'),
      array('id' => '3', 'category_id' => '71', 'title' => 'Content Scheduling and Optimization', 'slug' => 'track-your-marketing-to-see-the-best-results', 'icon' => '/demo/TD3r9iasG0leHuCTP0rw.svg', 'preview' => '/demo/nR0AKgx359bH7qDJ7LW9.jpg', 'overview' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'description' => NULL, 'faqs' => NULL, 'is_active' => '1', 'is_featured' => '1', 'meta' => '{"title":"Content Scheduling and Optimization","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}', 'created_at' => '2023-11-03 02:57:49', 'updated_at' => '2024-08-15 04:57:58'),
      array('id' => '4', 'category_id' => '72', 'title' => 'Grow with AI', 'slug' => 'automate-recurring-invoices-and-save-time', 'icon' => '/demo/gwn5sTjxXNOGD0hn7c6E.svg', 'preview' => '/demo/7ishcatt6WES014ttzO4.jpg', 'overview' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'description' => NULL, 'faqs' => NULL, 'is_active' => '1', 'is_featured' => '1', 'meta' => '{"title":"Generate, Manage, and Convert leads into Customers. Automatically","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}', 'created_at' => '2023-11-05 02:57:49', 'updated_at' => '2024-08-15 04:58:33'),
      array('id' => '5', 'category_id' => '73', 'title' => '24/7 Activity Monitoring and Engagement', 'slug' => 'get-real-time-visibility-into-every-expense', 'icon' => '/demo/eqq6Fo99OuUJCd3AXVyX.svg', 'preview' => '/demo/xnDMRgHGqNkTnYBpCbVY.jpg', 'overview' => '<div class="mb-30 sv-details-title-box"><h4 class=sv-details-title>Service Overview</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div><div class="mb-30 sv-details-text"><h4 class="sv-details-text-title pb-10">Going Beyond the Usual</h4><ul><li><i class="fa-check fal"></i><p>Product Quality:<br><span>Automatically syncs across all your devices. You can also access....</span><li><i class="fa-check fal"></i><p>On Demand Design:<br><span>Images, videos, PDFs and audio files are supported.</span><li><i class="fa-check fal"></i><p>Choice of Service: <span>Whatever your business needs, you can choose a service.</span></ul></div><div class=sv-details-text-2><h4 class=sv-details-text-title>The Challange</h4><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum, orci at dapibus, massa ante pharetra tellus. Maecenas interdum, orci at euismod dapibus. Lorem ipsum dolor sit amet!</div>', 'description' => NULL, 'faqs' => NULL, 'is_active' => '1', 'is_featured' => '1', 'meta' => '{"title":"24\\/7 Activity Monitoring and Engagement","image":null,"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas interdum","tags":"service,stori,ai"}', 'created_at' => '2023-11-15 02:57:49', 'updated_at' => '2024-08-15 04:58:41')
    );

    Service::insert($services);
  }
}
